; ShowOffNVSE Tweaks INI
; New options are generated when the game is launched

[INI]

; sort the ini alphabetically
bSortAlphabetically = 0

; add new settings to the top of the ini
bPrependNewSettings = 1



